server:
  port: 8088

spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 30
        queue-capacity: 1000
      thread-name-prefix: migrate-

app:
  datasource:
    mysql:
#      url: jdbc:mysql://10.84.86.33:3306/common_hnd?tinyInt1isBit=false
#      username: rdvivas
#      password: rdvivas@123
      url: jdbc:mysql://localhost:3306/common_hnd?createDatabaseIfNotExist=true
      username: ${MYSQL_ROOT_USERNAME:root}
      password: ${MYSQL_ROOT_PASSWORD:abc@123}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connectionTimeout: 10000
        idleTimeout: 20000
        maxLifetime: 60000
        maxPoolSize: 5

    oracle:
      url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.84.5.74)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=tnvn)))
      username: ${MYSQL_ROOT_USERNAME:tnvn}
      password: ${MYSQL_ROOT_PASSWORD:tnvn#123}
      driver-class-name: oracle.jdbc.driver.OracleDriver
      hikari:
        connectionTimeout: 10000
        idleTimeout: 20000
        maxLifetime: 60000
        maxPoolSize: 5

logging:
  level:
    org:
      hibernate:
        SQL: INFO
  config: logback.xml


